### ISSUE TITLE
font imported via css-in-js in app.js (fontsource)

### ISSUE THREAD

**Issue by weber-s** [jeffreyvr/tailpress#253]
Hello!

In my app.js, I have the following:

```js
import "@fontsource/poppins/latin.css";
```

And the tailwindconfig looks like:

```js
const theme = require('./theme.json');
const tailpress = require("@jeffreyvr/tailwindcss-tailpress");

/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
        './*.php',
        './**/*.php',
        './resources/css/*.css',
        './resources/js/*.js',
        './safelist.txt'
    ],
    theme: {
        extend: {
            colors: tailpress.colorMapper(tailpress.theme('settings.color.palette', theme)),
            fontSize: tailpress.fontSizeMapper(tailpress.theme('settings.typography.fontSizes', theme))
        },
        fontFamily: {
            'sans': ['Poppins'],
        },
   }
}
```

So nothing special here.

The fonts are well extracted in the <theme>/fonts/ directory.

But the @font-face generated are wrong:

```css
/* poppins-latin-100-normal */
@font-face {
  font-family: 'Poppins';
  font-style: normal;
  font-display: swap;
  font-weight: 100;
  src: url(../fonts/vendor/@fontsource/poppins/files/poppins-latin-100-normal.woff2?e1fac90e97bbc430e963e211260967fd) format('woff2'), url(../fonts/vendor/@fontsource/poppins/files/poppins-latin-100-normal.woff?bc3511f17a1f62b5ff5d0f5b19144d10) format('woff');
}
```

The browser try to locate them in 

`http://mysite/fonts/vendor/@fontsource/poppins/files/poppins-latin-100-normal.woff2`
or even in
`http://mysite/post/fonts/vendor/@fontsource/poppins/files/poppins-latin-100-normal.woff2`

instead of

`http://mysite/wp-content/themes/<theme>/fonts/vendor/@fontsource/poppins/files/poppins-latin-100-normal.woff2`

Any idea how to fix it? I dont know if it's a css-in-js config issue, webpack one, or whatever...

edit: using default fonts in the resource folder does work (https://github.com/jeffreyvr/tailpress-custom-font-example)
